import type { BuiltinFunction, FormulaProperty } from "./types";

// ── Tokenizer for basic syntax highlighting ───────────────────────────────────
export const FUNCTION_NAMES = new Set([
  "if",
  "and",
  "or",
  "not",
  "empty",
  "concat",
  "contains",
  "replace",
  "replaceAll",
  "length",
  "slice",
  "split",
  "lower",
  "upper",
  "trim",
  "test",
  "format",
  "abs",
  "ceil",
  "floor",
  "round",
  "max",
  "min",
  "sqrt",
  "pow",
  "log",
  "mod",
  "toNumber",
  "now",
  "today",
  "dateAdd",
  "dateBetween",
  "year",
  "month",
  "day",
  "date",
  "hour",
  "minute",
  "timestamp",
  "fromTimestamp",
  "at",
  "first",
  "last",
  "sort",
  "reverse",
  "join",
  "includes",
  "filter",
  "map",
  "count",
  "prop",
]);

export const DEFAULT_PROPERTIES: FormulaProperty[] = [
  { id: "name", name: "Name", type: "text" },
  { id: "created_by", name: "Created By", type: "created_by" },
  { id: "created_time", name: "Created Time", type: "created_time" },
  { id: "edited_by", name: "Last Edited By", type: "edited_by" },
  { id: "edited_time", name: "Last Edited Time", type: "edited_time" },
];

export const BUILTIN_FUNCTIONS: BuiltinFunction[] = [
  // Logic
  {
    name: "if",
    category: "logic",
    signature: "if(condition, trueValue, falseValue)",
    description: "Returns one of two values based on a condition.",
    example: 'if(1 > 0, "yes", "no")',
  },
  {
    name: "and",
    category: "logic",
    signature: "and(a, b)",
    description: "Returns true if both arguments are true.",
    example: "and(true, true)",
  },
  {
    name: "or",
    category: "logic",
    signature: "or(a, b)",
    description: "Returns true if either argument is true.",
    example: "or(false, true)",
  },
  {
    name: "not",
    category: "logic",
    signature: "not(value)",
    description: "Negates a boolean value.",
    example: "not(false)",
  },
  {
    name: "empty",
    category: "logic",
    signature: "empty(value)",
    description: "Returns true if the value is empty.",
    example: 'empty("")',
  },

  // Text
  {
    name: "concat",
    category: "text",
    signature: "concat(a, b, ...)",
    description: "Joins strings together.",
    example: 'concat("Hello", " ", "World")',
  },
  {
    name: "contains",
    category: "text",
    signature: "contains(text, substring)",
    description: "Returns true if text contains substring.",
    example: 'contains("hello", "ell")',
  },
  {
    name: "replace",
    category: "text",
    signature: "replace(text, search, replace)",
    description: "Replaces first occurrence in a string.",
    example: 'replace("foo bar", "foo", "baz")',
  },
  {
    name: "replaceAll",
    category: "text",
    signature: "replaceAll(text, search, replace)",
    description: "Replaces all occurrences in a string.",
    example: 'replaceAll("a-b-c", "-", "/")',
  },
  {
    name: "length",
    category: "text",
    signature: "length(text)",
    description: "Returns the number of characters.",
    example: 'length("hello")',
  },
  {
    name: "slice",
    category: "text",
    signature: "slice(text, start, end?)",
    description: "Extracts a portion of a string.",
    example: 'slice("hello", 1, 3)',
  },
  {
    name: "split",
    category: "text",
    signature: "split(text, separator)",
    description: "Splits a string into an array.",
    example: 'split("a,b,c", ",")',
  },
  {
    name: "lower",
    category: "text",
    signature: "lower(text)",
    description: "Converts to lowercase.",
    example: 'lower("HELLO")',
  },
  {
    name: "upper",
    category: "text",
    signature: "upper(text)",
    description: "Converts to uppercase.",
    example: 'upper("hello")',
  },
  {
    name: "trim",
    category: "text",
    signature: "trim(text)",
    description: "Removes leading and trailing whitespace.",
    example: 'trim("  hello  ")',
  },
  {
    name: "test",
    category: "text",
    signature: "test(text, regex)",
    description: "Tests if text matches a regex pattern.",
    example: 'test("hello123", "\\\\d+")',
  },
  {
    name: "format",
    category: "text",
    signature: "format(value)",
    description: "Converts any value to a string.",
    example: "format(42)",
  },

  // Number
  {
    name: "abs",
    category: "number",
    signature: "abs(number)",
    description: "Returns the absolute value.",
    example: "abs(-5)",
  },
  {
    name: "ceil",
    category: "number",
    signature: "ceil(number)",
    description: "Rounds up to the nearest integer.",
    example: "ceil(4.2)",
  },
  {
    name: "floor",
    category: "number",
    signature: "floor(number)",
    description: "Rounds down to the nearest integer.",
    example: "floor(4.8)",
  },
  {
    name: "round",
    category: "number",
    signature: "round(number)",
    description: "Rounds to the nearest integer.",
    example: "round(4.5)",
  },
  {
    name: "max",
    category: "number",
    signature: "max(a, b, ...)",
    description: "Returns the largest value.",
    example: "max(1, 5, 3)",
  },
  {
    name: "min",
    category: "number",
    signature: "min(a, b, ...)",
    description: "Returns the smallest value.",
    example: "min(1, 5, 3)",
  },
  {
    name: "sqrt",
    category: "number",
    signature: "sqrt(number)",
    description: "Returns the square root.",
    example: "sqrt(16)",
  },
  {
    name: "pow",
    category: "number",
    signature: "pow(base, exponent)",
    description: "Raises a number to a power.",
    example: "pow(2, 8)",
  },
  {
    name: "log",
    category: "number",
    signature: "log(number, base?)",
    description: "Returns the logarithm.",
    example: "log(100, 10)",
  },
  {
    name: "mod",
    category: "number",
    signature: "mod(dividend, divisor)",
    description: "Returns the remainder of division.",
    example: "mod(10, 3)",
  },
  {
    name: "toNumber",
    category: "number",
    signature: "toNumber(value)",
    description: "Converts a value to a number.",
    example: 'toNumber("42")',
  },

  // Date
  {
    name: "now",
    category: "date",
    signature: "now()",
    description: "Returns the current date and time.",
    example: "now()",
  },
  {
    name: "today",
    category: "date",
    signature: "today()",
    description: "Returns today's date.",
    example: "today()",
  },
  {
    name: "dateAdd",
    category: "date",
    signature: "dateAdd(date, number, unit)",
    description: "Adds time to a date.",
    example: 'dateAdd(now(), 7, "days")',
  },
  {
    name: "dateBetween",
    category: "date",
    signature: "dateBetween(date1, date2, unit)",
    description: "Returns the difference between two dates.",
    example: 'dateBetween(now(), today(), "hours")',
  },
  {
    name: "year",
    category: "date",
    signature: "year(date)",
    description: "Returns the year.",
    example: "year(now())",
  },
  {
    name: "month",
    category: "date",
    signature: "month(date)",
    description: "Returns the month (0–11).",
    example: "month(now())",
  },
  {
    name: "day",
    category: "date",
    signature: "day(date)",
    description: "Returns the day of week (0–6).",
    example: "day(now())",
  },
  {
    name: "date",
    category: "date",
    signature: "date(date)",
    description: "Returns the day of month.",
    example: "date(now())",
  },
  {
    name: "hour",
    category: "date",
    signature: "hour(date)",
    description: "Returns the hour.",
    example: "hour(now())",
  },
  {
    name: "minute",
    category: "date",
    signature: "minute(date)",
    example: "minute(now())",
    description: "Returns the minute.",
  },
  {
    name: "timestamp",
    category: "date",
    signature: "timestamp(date)",
    description: "Returns Unix timestamp in ms.",
    example: "timestamp(now())",
  },
  {
    name: "fromTimestamp",
    category: "date",
    signature: "fromTimestamp(ms)",
    description: "Converts ms timestamp to a date.",
    example: "fromTimestamp(0)",
  },

  // Array
  {
    name: "at",
    category: "array",
    signature: "at(array, index)",
    description: "Returns the item at the given index.",
    example: 'at(split("a,b,c", ","), 0)',
  },
  {
    name: "first",
    category: "array",
    signature: "first(array)",
    description: "Returns the first item.",
    example: 'first(split("a,b", ","))',
  },
  {
    name: "last",
    category: "array",
    signature: "last(array)",
    description: "Returns the last item.",
    example: 'last(split("a,b", ","))',
  },
  {
    name: "sort",
    category: "array",
    signature: "sort(array)",
    description: "Sorts an array.",
    example: 'sort(split("c,a,b", ","))',
  },
  {
    name: "reverse",
    category: "array",
    signature: "reverse(array)",
    description: "Reverses an array.",
    example: 'reverse(split("a,b,c", ","))',
  },
  {
    name: "join",
    category: "array",
    signature: "join(array, separator)",
    description: "Joins an array into a string.",
    example: 'join(split("a,b,c", ","), "-")',
  },
  {
    name: "includes",
    category: "array",
    signature: "includes(array, value)",
    description: "Returns true if array contains value.",
    example: 'includes(split("a,b,c", ","), "b")',
  },
  {
    name: "filter",
    category: "array",
    signature: "filter(array, fn)",
    description: "Returns items matching a condition.",
    example: "",
  },
  {
    name: "map",
    category: "array",
    signature: "map(array, fn)",
    description: "Transforms each item in an array.",
    example: "",
  },
  {
    name: "count",
    category: "array",
    signature: "count(array)",
    description: "Returns the number of items.",
    example: 'count(split("a,b,c", ","))',
  },
];

export const BUILTIN_CATEGORIES = [
  "logic",
  "text",
  "number",
  "date",
  "array",
] as const;

export const CATEGORY_LABELS: Record<string, string> = {
  logic: "Logic",
  text: "Text",
  number: "Number",
  date: "Date",
  array: "Array",
};
